@startuml Bunchart Class Diagram

'skinparam Shadowing false
'skinparam Monochrome true

class Person {
    -name: string
    +age: number
    -photos: [Photo]
    constructor(name: string, age: number)
    addPhoto(photo: Photo)
    likePhoto(photo: Photo)
}

class Artwork {
    filename: string
    likeBy: {Person}
    constructor(filename: string)
}

class Auction {
    category: string
    bidders: {Person}
    presentedArtworks: [artworkId]
    constructor(category: string)
}

class House {}

Person "1" o---> "0..*" Artwork : keeps, likes
Artwork  ---> "0..*" Person : liked by

package PersonActions {
    class Person {}
    class Artwork {}
    class Auction {}
}

Person *- Artwork
Artwork o--> Auction

Person -> Artwork : upload

package Payment {
    class House {}
    class Payment extends House {}
    class Taxes extends House {}
    class Billing extends House {}
    class Shipping extends House{}
}

Payment --> Taxes : add
Payment --> Billing : print
Shipping ---> Artwork
Payment <---> Person
Person --> Auction



@enduml